### ISSUE TITLE
How to access the site component

### ISSUE THREAD

**Issue by atticoos** [pagekit/extension-hello#3]
So I've installed this package to try and understand how extensions work.

I can see how the backend controller, `HelloController` is working. However, `SiteController` I am at a loss. Based on the route names, and the node name, I figured I could access the following:
- `/hello` :arrow_right: `SiteController indexAction`
- `/hello/greet/fakename` :arrow_right: `SiteController greetAction`
- `/hello/json` :arrow_right: `SiteController jsonAction`
  etc

But none of these routes appear to be available. I've compared this to the blog extension and the `nodes` section of `index.php` appears to be set up similarly that it should be accessible. Am I doing something wrong?

**Comment by polyrythmie** [comment]
After a lot of working through the same problem, I think it's partly to do with not pulling from the develop branch. Yesterday extension-hello did not work for me, today I reinstalled everything, and now it works.

**Comment by atticoos** [comment]
Good to know. I didn't realize until recently, as mentioned in https://github.com/pagekit/pagekit/issues/462, they had undergone a large restructuring.

Going to close as this is likely just an issue with the package being out of date against the latest version of the platform
